apiVersion: v1
kind: PersistentVolume
metadata:
  name: d-rj9apo0hv7sz10i3a1bh
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  flexVolume:
    driver: "alicloud/disk"
    fsType: "ext4"
    options:
      volumeId: "d-rj9apo0hv7sz10i3a1bh"